In [6]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import sklearn.linear_model

In [8]:
LR=sklearn.linear_model.LogisticRegression

In [9]:
#load data
claims=pd.read_csv('claimants.csv')
claims.head()

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        5         0     0.0       1.0       0.0    50.0  34.940
1        3         1     1.0       0.0       0.0    18.0   0.891
2       66         1     0.0       1.0       0.0     5.0   0.330
3       70         0     0.0       1.0       1.0    31.0   0.037
4       96         1     0.0       1.0       0.0    30.0   0.038

In [10]:
#eda
claims.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   CASENUM   1340 non-null   int64  
 1   ATTORNEY  1340 non-null   int64  
 2   CLMSEX    1328 non-null   float64
 3   CLMINSUR  1299 non-null   float64
 4   SEATBELT  1292 non-null   float64
 5   CLMAGE    1151 non-null   float64
 6   LOSS      1340 non-null   float64
dtypes: float64(5), int64(2)
memory usage: 73.4 KB


In [12]:
#droping 
c1=claims.drop(columns='CASENUM')

In [13]:
c1

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0            0     0.0       1.0       0.0    50.0  34.940
1            1     1.0       0.0       0.0    18.0   0.891
2            1     0.0       1.0       0.0     5.0   0.330
3            0     0.0       1.0       1.0    31.0   0.037
4            1     0.0       1.0       0.0    30.0   0.038
...        ...     ...       ...       ...     ...     ...
1335         1     0.0       1.0       0.0     NaN   0.576
1336         0     1.0       1.0       0.0    46.0   3.705
1337         1     1.0       1.0       0.0    39.0   0.099
1338         0     1.0       0.0       0.0     8.0   3.177
1339         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 6 columns]

In [23]:
c1=c1.drop(columns="CASENUM")
c1.head()


ATTORNEY  CLMSEX  CLMINSUR  SEATBELT
0         0     0.0       1.0       0.0
1         1     1.0       0.0       0.0
2         1     0.0       1.0       0.0
3         0     0.0       1.0       1.0
4         1     0.0       1.0       0.0

In [25]:
c1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ATTORNEY  1340 non-null   int64  
 1   CLMSEX    1328 non-null   float64
 2   CLMINSUR  1299 non-null   float64
 3   SEATBELT  1292 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 42.0 KB


In [33]:
#dropping null
c1=c1.dropna(axis=0)

In [34]:
c1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1269 entries, 0 to 1339
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   ATTORNEY  1269 non-null   int64  
 1   CLMSEX    1269 non-null   float64
 2   CLMINSUR  1269 non-null   float64
 3   SEATBELT  1269 non-null   float64
dtypes: float64(3), int64(1)
memory usage: 49.6 KB


In [35]:
#dividing data
c1.head()

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT
0         0     0.0       1.0       0.0
1         1     1.0       0.0       0.0
2         1     0.0       1.0       0.0
3         0     0.0       1.0       1.0
4         1     0.0       1.0       0.0

In [69]:
X=c1.iloc[:,1:4]
Y=c1.iloc[:,0]

y

0       0
1       1
2       1
3       0
4       1
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1269, dtype: int64

In [71]:
#model 'ArithmeticError
classifier=LR()
classifier.fit(X,Y)


LogisticRegression()

In [72]:
classifier

LogisticRegression()

In [73]:
classifier.coef_

array([[ 0.32017633,  0.55451956, -0.79637515]])

In [74]:
#fitter value
classifier.predict(X)

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [76]:
a=pd.Series(classifier.predict(X))
a

0       0
1       0
2       0
3       0
4       0
       ..
1264    0
1265    1
1266    1
1267    0
1268    1
Length: 1269, dtype: int64

In [77]:
#compareing actual and predicted
c1['P']=a

In [79]:
c1[0:30]

ATTORNEY  CLMSEX  CLMINSUR  SEATBELT    P
0          0     0.0       1.0       0.0  0.0
1          1     1.0       0.0       0.0  0.0
2          1     0.0       1.0       0.0  0.0
3          0     0.0       1.0       1.0  0.0
4          1     0.0       1.0       0.0  0.0
5          0     1.0       1.0       0.0  1.0
6          0     0.0       1.0       0.0  0.0
7          0     1.0       1.0       0.0  1.0
8          1     1.0       1.0       0.0  1.0
9          1     0.0       1.0       0.0  0.0
10         0     1.0       1.0       0.0  1.0
11         0     0.0       1.0       0.0  0.0
12         1     0.0       1.0       0.0  0.0
13         0     1.0       1.0       0.0  1.0
14         1     1.0       1.0       0.0  1.0
15         1     1.0       0.0       0.0  0.0
16         1     1.0       1.0       0.0  1.0
17         0     0.0       1.0       0.0  0.0
18         1     0.0       1.0       0.0  0.0
19         0     1.0       1.0       0.0  1.0
21         1     1.0       1.0       0.0  0.0
22         0     0.0       0.0       0.0  0.0
24         1     0.0       1.0       0.0  0.0
25         1     1.0       1.0       0.0  0.0
26         1     0.0       1.0       0.0  0.0
27         0     0.0       1.0       0.0  0.0
28         1     0.0       1.0       0.0  1.0
29         0     0.0       1.0       0.0  0.0
30         1     1.0       1.0       0.0  0.0
31         1     0.0       1.0       0.0  1.0

In [82]:
classifier.predict_proba(X)


array([[0.53732534, 0.46267466],
       [0.5948189 , 0.4051811 ],
       [0.53732534, 0.46267466],
       ...,
       [0.45745396, 0.54254604],
       [0.5948189 , 0.4051811 ],
       [0.45745396, 0.54254604]])